spring.application.name=servicehub
spring.datasource.url=jdbc:mysql://localhost:3306/servicehub
spring.datasource.username=root
spring.datasource.password=Shree@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true